import std/[strutils, tables, times, macros, os]

import pkg/supranim/core/servicemanager
import pkg/supranim/core/paths

## This service provider implements a static assets bundler,
## allowing you to embed files (like images, CSS, JS) directly into your Supranim application binary.
## 
## It provides a simple API to add assets at compile-time and retrieve them at runtime.
## Basically, this service provider is a convenient way to manage static resources without needing to read from the filesystem at runtime.
## 
## The `embedAssets` macro can be used to embed all files from a specified directory,
## and the service will automatically determine if they are plain text or binary based on a simple heuristic.
## 
## This is particularly useful for serving static content in web applications or bundling resources for CLI tools.

initService Assets[Singleton]:
  backend do:

    type
      Assets = object
        files: Table[string, seq[uint8]] = initTable[string, seq[uint8]]()
        textFiles: Table[string, string] = initTable[string, string]()

      StaticAssetsError* = object of CatchableError

    proc isPlainText*(data: openArray[uint8], sampleSize = 8192): bool =
      ## Fast heuristic (not perfect)
      let n = min(data.len, sampleSize)
      if n == 0: return true
      var ctrl = 0
      for i in 0..<n:
        let b = data[i]
        if b == 0'u8:          # NUL => almost certainly binary
          return false
        # Allow common whitespace: TAB(9), LF(10), VT(11), FF(12), CR(13)
        if (b < 9'u8) or (b >= 14'u8 and b < 32'u8) or (b == 127'u8):
          inc ctrl
      # Threshold: >2% suspicious control chars => binary
      result = (ctrl * 100 div n) <= 2

  client do:
    proc staticAssets*(): ptr Assets {.inline.} =
      ## Returns the Singleton instance of the Assets service
      getAssetsInstance() # auto generated by the service manager

    proc hasAsset*(sta: ptr Assets, key: string): bool =
      ## Checks if an embedded asset exists for the given key
      sta[].files.hasKey(key)

    proc get*(sta: ptr Assets, key: string): lent seq[uint8] =
      ## Retrieve an embedded asset by its key (relative path)
      if sta[].files.hasKey(key):
        return sta[].files[key]
      raise newException(StaticAssetsError, "Asset not found: " & key)
    
    proc hasAssetString*(sta: ptr Assets, key: string): bool =
      ## Checks if a text asset exists for the given key
      sta[].textFiles.hasKey(key)

    proc getAssetString*(sta: ptr Assets, key: string): string =
      ## Fast path for text assets; fallback to byte->string copy
      if sta[].textFiles.hasKey(key):
        return sta[].textFiles[key]
      raise newException(StaticAssetsError, "Text asset not found: " & key)

    proc addAsset*(sta: ptr Assets, key: string, data: seq[uint8]) =
      ## Add an asset to the StaticBundle (used at compile-time)
      if sta[].files.hasKey(key):
        raise newException(StaticAssetsError, "Asset already exists: " & key)
      sta[].files[key] = data

    proc addTextAsset*(sta: ptr Assets, key: string, data: string) =
      ## Add plain-text asset
      sta[].textFiles[key] = data

    macro embedAssets*(dir: static string): untyped =
      result = newStmtList()
      for kind, path in walkDir(joinPath(storagePath, dir)):
        if kind == pcFile:
          if path.isHidden: continue # skip hidden files
          let fileText = staticRead(path)
          let relPath = path.replace(storagePath, "")
          let key = relPath.replace("\\", "/")
          # Build bytes once
          var bytes = newSeq[uint8](fileText.len)
          var byteElems = newNimNode(nnkBracket)
          for i, ch in fileText:
            let b = uint8(ord(ch))
            bytes[i] = b
            byteElems.add(newLit(b))
          if isPlainText(bytes):
            result.add(
              nnkCall.newTree(
                nnkDotExpr.newTree(
                  nnkCall.newTree(
                    ident"staticAssets"
                  ),
                  ident"addTextAsset"
                ),
                newLit(key), newLit(fileText)
              )
            )
          else:
            result.add(
              nnkCall.newTree(
                nnkDotExpr.newTree(
                  nnkCall.newTree(
                    ident"staticAssets"
                  ),
                  ident"addAsset"
                ),
                newLit(key),
                nnkPrefix.newTree(ident"@", byteElems)
              )
            )