#
# Supranim is a high-performance web framework for building
# web applications and microservices in Nim
# 
#   (c) 2026 LGPL-v3-or-later License | Made by Humans from OpenPeeps
#   https://supranim.com | https://github.com/supranim
#
import std/[strutils, tables, times, macros, os, macrocache]

import pkg/supranim/core/services
import pkg/supranim/core/paths

## This service provider implements a static assets bundler,
## allowing you to embed files (like images, CSS, JS) directly into your Supranim application binary.
## 
## It provides a simple API to add assets at compile-time and retrieve them at runtime.
## Basically, this service provider is a convenient way to manage static resources without needing to read from the filesystem at runtime.
## 
## The `embedAssets` macro can be used to embed all files from a specified directory,
## and the service will automatically determine if they are plain text or binary based on a simple heuristic.
## 
## This is particularly useful for serving static content in web applications or bundling resources for CLI tools.

initService Assets[Singleton]:
  backend do:
    type
      BinFilesTable = TableRef[string, seq[uint8]]
      TextFilesTable = TableRef[string, string]
      TextFilesDirTable = TableRef[string, TableRef[string, string]]
      
      Assets = object
        files: BinFilesTable
        textFilesDir: TextFilesDirTable

      StaticAssetsError* = object of CatchableError

    proc isPlainText*(data: openArray[uint8], sampleSize = 8192): bool =
      ## Fast heuristic (not perfect)
      let n = min(data.len, sampleSize)
      if n == 0: return true
      var ctrl = 0
      for i in 0..<n:
        let b = data[i]
        if b == 0'u8:          # NUL => almost certainly binary
          return false
        # Allow common whitespace: TAB(9), LF(10), VT(11), FF(12), CR(13)
        if (b < 9'u8) or (b >= 14'u8 and b < 32'u8) or (b == 127'u8):
          inc ctrl
      # Threshold: >2% suspicious control chars => binary
      result = (ctrl * 100 div n) <= 2

  client do:
    proc staticAssets*: ptr Assets {.inline.} =
      ## Returns the Singleton instance of the Assets service
      getAssetsInstance(
        proc(instance: ptr Assets) =
          {.gcsafe.}:
            instance[] = Assets()
            instance[].files = newTable[string, seq[uint8]]()
            instance[].textFilesDir = newTable[string, TableRef[string, string]]()
      ) # auto generated by the service manager
    
    #
    # bin files
    #
    proc hasAsset*(sta: ptr Assets, key: string): bool =
      ## Checks if an embedded asset exists for the given key
      sta[].files.hasKey(key)

    proc get*(sta: ptr Assets, key: string): lent seq[uint8] =
      ## Retrieve an embedded asset by its key (relative path)
      if sta[].files.hasKey(key):
        return sta[].files[key]
      raise newException(StaticAssetsError, "Asset not found: " & key)

    proc addAsset*(sta: ptr Assets, key: string, data: seq[uint8]) =
      ## Add an asset to the StaticBundle (used at compile-time)
      if sta[].files.hasKey(key):
        raise newException(StaticAssetsError, "Asset already exists: " & key)
      sta[].files[key] = data

    #
    # plaintext files
    #
    proc directory*(sta: ptr Assets, key: string): TableRef[string, string] =
      ## Get a directory of text assets by key
      if sta[].textFilesDir.hasKey(key):
        return sta[].textFilesDir[key]
      raise newException(StaticAssetsError, "Text asset directory not found: " & key)

    proc getTextFile*(dir: TextFilesTable, key: string): string =
      ## Get a text asset by key from a directory
      if dir.hasKey(key):
        return dir[key]
      raise newException(StaticAssetsError, "Text asset not found in directory: " & key)

    proc addTextFile*(sta: ptr Assets, dir: string, key: string, data: sink string) =
      ## Add a text asset to a directory in the StaticBundle
      if sta[].textFilesDir == nil:
        sta[].textFilesDir = TextFilesDirTable()
      if not sta[].textFilesDir.hasKey(dir):
        sta[].textFilesDir[dir] = TextFilesTable()
      sta[].textFilesDir[dir][key] = data

    proc hasFile*(filesDir: TextFilesTable, key: string): bool =
      ## Check if a text asset exists in a directory
      result = filesDir.hasKey(key)

    proc getFile*(filesDir: TextFilesTable, key: string): string =
      ## Get a text asset from a directory
      if filesDir.hasKey(key):
        return filesDir[key]
      raise newException(StaticAssetsError, "Text asset not found in directory: " & key)

    const AssetsImportStmt* = CacheTable"AssetsImportStmt"
    macro embedAssets*(dir: static string): untyped =
      ## Embed all files from the specified directory into the application binary.
      ## 
      ## Use `supra bundle.assets <dir> <output>` command to generate the embedded assets file.
      let srcDir = joinPath(storagePath, dir)
      let safeName = dir.replace("\\", "_").replace("/", "_")
      let outFile = joinPath(cachePath, "embed_" & safeName & ".nim")
      AssetsImportStmt["assets"] = nnkImportStmt.newTree(newLit(outFile))

    macro embedDirectory*(dir: static string, key: static string) =
      ## Embed all files from the specified directory into the application binary.
      ## This is a more flexible version of `embedAssets` that allows you to specify a
      ## directory outside of the Supranim storage path.
      let safeName = splitPath(dir).tail
      let outFile = joinPath(cachePath, "embed_" & safeName & ".nim")
      AssetsImportStmt[key] = nnkImportStmt.newTree(newLit(outFile))

    macro preloadAssets*: untyped =
      ## Preloads assets at runtime (if needed). This can be used to trigger any lazy loading logic.
      result = AssetsImportStmt["loadBundler"]

    macro preloadBundle*(key: static string): untyped = 
      ## Preloads templates at runtime (if needed). This can be used to trigger any lazy loading logic.
      if not AssetsImportStmt.hasKey(key):
        error("No embedded assets found for key: " & key)
      result = AssetsImportStmt[key]