--path:"/Users/georgelemon/Development/packages/supranim/src"
--path:"/Users/georgelemon/Development/packages/openparser/src"
--define:release
--define:supraDebugServiceProviderCode
--out:"./bin/cacheable"
