# Supranim - A fast MVC web framework
# for building web apps & microservices in Nim.
#
#   (c) 2025 MIT License | Made by Humans from OpenPeeps
#   https://supranim.com | https://github.com/supranim

import pkg/supranim/core/services

import pkg/[emitter, libevent/bindings/threaded]
export emitter

## The `events` service provides a global event emitter that can be used
## throughout the application to emit and listen for custom events. It uses
## the `emitter` package for efficient event handling with Libevent.

initService EventEmitter[Singleton]:
  ## A singleton of the EventEmitter `emitter` package.
  ## It allows different parts of the application to register listeners
  ## for specific events and emit those events with optional arguments.
  client do:
    proc event*: ptr EventEmitter {.inline.} =
      ## Returns the Singleton instance of the EventManager
      getEventEmitterInstance(
        proc(instance: ptr EventEmitter) =
          {.gcsafe.}:
            new(instance[])
            instance[].init() # initialize the EventEmitter instance when it's created
      ) # auto generated by the service manager
    
    proc runEventThread {.thread.} =
      event().run()
    var thr: Thread[void]
    
    proc init*() =
      assert evthread_use_pthreads() == 0
      createThread(thr, runEventThread)

    macro listener*(eventName: static string; handle: untyped): untyped =
      ## This macro is used to register an event listener
      ## for a specific event. The `eventName` is the name
      ## of the event, and `description` is an optional
      ## description of the event.
      result = newCall(
        ident"registerListener",
        nnkBracketExpr.newTree(newCall(ident"event")),
        newLit(eventName),
        newProc(
          params = [
            newEmptyNode(),
            nnkIdentDefs.newTree(
              ident"args",
              nnkBracketExpr.newTree(ident"Option", ident"Args"),
              nnkCall.newTree(ident"none", ident"Args") # default
            ),
          ],
          body = handle,
          pragmas = nnkPragma.newTree(
            ident"nimcall",
            ident"thread",
          )
        ),
        ident"AnyTime"
      )