name: test
on: [push, pull_request]
jobs:
  test:
    uses: nimbase/setup-nim-action/.github/workflows/test.yml@main

# - name: Install supra CLI
#   run: nimble install https://github.com/supranim/supra -Y

# - name: Create a test project with supra
#   run: |
#     git config --global user.name "CI"
#     supra init testapp --skipconfig --nocache
#     cd testapp
#     git init
#   env:
#     DYLD_LIBRARY_PATH: /usr/local/opt/libpq/lib:$DYLD_LIBRARY_PATH

# - name: Build the test project
#   run: nimble build
#   working-directory: testapp
#   env:
#     DYLD_LIBRARY_PATH: /usr/local/opt/libpq/lib:$DYLD_LIBRARY_PATH
